<a href="https://colab.research.google.com/github/pxs1990/Data_Science_projects/blob/main/NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Natural Language Processing:makes machine interact with humans**

Natural Language Processing (NLP) is a subfield of artificial intelligence (AI) that focuses on the interaction between computers and human languages. The goal of NLP is to enable computers to understand, interpret, and generate human language in a way that is both meaningful and contextually relevant.

 *Natural Language Processing (NLP) is a branch of technology that focuses on making computers understand and interact with human language—just like we humans do. It involves teaching computers to read, interpret, and respond to text or speech in a way that feels natural to us. Applications like Alexa, Siri,google translate, chatbots etc utilize Natural Language Processing (NLP) as a fundamental component of their functionality.*

NLP involves a range of tasks and challenges, including:

1. **Text Understanding:** This includes tasks such as parsing, part-of-speech tagging, and named entity recognition, where the system identifies the grammatical structure and extracts entities like names, locations, and organizations from text.

2. **Machine Translation:** The automatic translation of text from one language to another is a classic NLP problem. Google Translate is a common example of a machine translation system.

3. **Speech Recognition:** Converting spoken language into written text is another area of NLP. Virtual assistants like Siri, Google Assistant, and Amazon Alexa use speech recognition to understand and respond to user commands.

4. **Text Generation:** NLP is also involved in generating human-like text. This can range from simple tasks like autocomplete suggestions to more complex tasks like writing coherent paragraphs or articles.

5. **Sentiment Analysis:** Determining the sentiment expressed in a piece of text, such as identifying whether a review is positive, negative, or neutral, is a common application of NLP.

6. **Question Answering:** Building systems that can understand and respond to questions posed in natural language. This is often seen in chatbots and virtual assistants.

7. **Summarization:** NLP systems can be used to automatically generate summaries of longer texts, making it easier for users to extract key information.

NLP applications are diverse and are used in various industries, including healthcare, finance, customer service, and more. The field continues to evolve with advancements in deep learning and other AI techniques, contributing to more accurate and sophisticated language understanding and generation by machines.




**Application:**
Natural Language Processing (NLP) finds applications in various domains, and its impact is widespread across different industries. Here are some common NLP applications:

1. **Virtual Assistants:** Virtual assistants like Siri, Google Assistant, and Amazon Alexa use NLP to understand and respond to user queries, making them capable of engaging in natural language conversations.

2. **Chatbots:** Businesses use NLP-powered chatbots to provide automated customer support. These chatbots can understand user queries, provide information, and even perform certain tasks without human intervention.

3. **Sentiment Analysis:** Companies use sentiment analysis to gauge the sentiment expressed in customer reviews, social media comments, or feedback. This information is valuable for understanding customer opinions and improving products or services.

4. **Language Translation:** NLP is at the core of machine translation systems like Google Translate, enabling the automatic translation of text from one language to another.

5. **Text Summarization:** NLP algorithms can be used to automatically generate concise summaries of longer texts, helping users quickly grasp the main points without reading the entire document.

6. **Named Entity Recognition (NER):** NLP is applied to identify and classify named entities in text, such as names of people, organizations, locations, dates, and more. This is useful in information extraction and analysis.

7. **Information Retrieval:** Search engines utilize NLP techniques to understand user queries and retrieve relevant information from vast databases.

8. **Speech Recognition:** NLP is integral to speech recognition systems, converting spoken language into written text. This is used in applications like voice assistants, transcription services, and voice-controlled devices.

9. **Text Classification:** NLP algorithms are employed for text classification tasks, such as spam detection, sentiment analysis, and topic categorization.

10. **Healthcare Informatics:** In the healthcare industry, NLP is used to extract valuable information from electronic health records, medical literature, and clinical notes, aiding in research and decision-making.

11. **Financial Analysis:** NLP helps analyze financial news, reports, and social media to gain insights into market trends, sentiments, and investment opportunities.

12. **Legal Document Analysis:** NLP can assist in processing and analyzing large volumes of legal documents, helping legal professionals with information retrieval and case analysis.

These applications showcase the versatility of NLP in enhancing human-computer interaction, automating tasks, and extracting valuable insights from vast amounts of unstructured textual data. The field continues to evolve, leading to new and innovative applications across various domains.

# **Components:**
Natural Language Processing (NLP) involves several components that work together to enable computers to understand, interpret, and generate human language. These components can vary in complexity and may be part of a larger NLP system. Here are some of the key components:

1. **Tokenization:**
   - **Definition:** Breaking down a text into smaller units, such as words or phrases.
   - **Purpose:** to facilitate further analysis by creating manageable units for processing.

2. **Part-of-Speech (POS) Tagging:**
   - **Definition:** Assigning part of speech (e.g., noun, verb, adjective) to each token in a sentence.
   - **Purpose:** To provide information about the syntactic structure of a sentence.

3. **Named Entity Recognition (NER):**
   - **Definition:** Identifying and classifying entities (e.g., names of people, organizations, locations) in a text.
   - **Purpose:** To extract specific information from text for further analysis.

4. **Parsing:**
   - **Definition:** Analyzing the grammatical structure of sentences to determine relationships between words.
   - **Purpose:** To help in understanding the syntactic structure of sentences.

5. **Semantic Analysis:**
   - **Definition:** Extracting the meaning of words, phrases, and sentences.
   - **Purpose:** To enable the system to understand the context and meaning behind the words.

6. **Coreference Resolution:**
   - **Definition:** Identifying when different words or expressions refer to the same entity.
   - **Purpose:** To improve the understanding of text by resolving references.

7. **Sentiment Analysis:**
   - **Definition:** Determining the sentiment expressed in a piece of text (e.g., positive, negative, neutral).
   - **Purpose:** To provide insights into opinions and attitudes expressed in textual data.

8. **Word Embeddings:**
   - **Definition:** Representing words as vectors in a high-dimensional space.
   - **Purpose:** To capture semantic relationships between words, facilitating similarity and contextual understanding.

9. **Machine Translation:**
   - **Definition:** Translating text from one language to another.
   - **Purpose:** To enable cross-language communication and information access.

10. **Speech Recognition:**
    - **Definition:** Converting spoken language into written text.
    - **Purpose:** To facilitate interaction with computers using voice commands.

11. **Text Generation:**
    - **Definition:** Creating human-like text based on given input or context.
    - **Purpose:** Useful for tasks such as content creation, chatbots, and dialogue systems.

12. **Information Retrieval:**
    - **Definition:** Retrieving relevant information from large datasets based on user queries.
    - **Purpose:** To enhance search engines and information access.

These components often work together in a pipeline, and advancements in machine learning, especially deep learning, have significantly improved the performance of NLP systems in recent years. NLP continues to be a dynamic field with ongoing research and development.


# **Libraries and Frameworks**
There are several powerful libraries and frameworks in the field of Natural Language Processing (NLP) that facilitate the development of language-based applications. Here are ten important libraries commonly used in NLP:

1. **NLTK (Natural Language Toolkit):**
   - **Description:** NLTK is a comprehensive library for working with human language data. It provides easy-to-use interfaces for tasks such as tokenization, stemming, tagging, parsing, and more. NLTK is widely used for educational purposes and research.

2. **Spacy:**
   - **Description:** Spacy is an open-source library designed for industrial-strength natural language processing. It is known for its efficiency and ease of use, offering pre-trained models for tasks such as part-of-speech tagging, named entity recognition, and dependency parsing.

3. **Gensim:**
   - **Description:** Gensim is a library for topic modeling and document similarity analysis. It is particularly popular for its implementation of algorithms like Latent Semantic Analysis (LSA) and Word2Vec, which are essential for understanding relationships between words.

4. **Transformers (Hugging Face):**
   - **Description:** The Transformers library by Hugging Face provides pre-trained models for a wide range of NLP tasks, including language translation, text summarization, sentiment analysis, and more. It is built on top of PyTorch and TensorFlow.

5. **BERT (Bidirectional Encoder Representations from Transformers):**
   - **Description:** BERT is a pre-trained transformer-based model developed by Google. The BERT library allows developers to use pre-trained BERT models for various NLP tasks, such as text classification and named entity recognition.

6. **TensorFlow NLP:**
   - **Description:** TensorFlow, a popular machine learning framework, has a dedicated NLP module that provides tools and resources for working on natural language processing tasks. It includes pre-trained models and various utilities for processing textual data.

7. **AllenNLP:**
   - **Description:** AllenNLP is a library built on top of PyTorch and designed for natural language understanding. It provides pre-built models for common NLP tasks and allows for easy experimentation and customization.

8. **TextBlob:**
   - **Description:** TextBlob is a simple and beginner-friendly library for processing textual data. It provides a consistent API for common NLP tasks, such as part-of-speech tagging, noun phrase extraction, sentiment analysis, classification, translation, and more.

9. **Stanford NLP:**
   - **Description:** The Stanford NLP toolkit is a collection of Java-based tools and software for natural language processing. It includes modules for tasks like part-of-speech tagging, named entity recognition, sentiment analysis, and coreference resolution.

10. **FastText:**
    - **Description:** FastText, developed by Facebook, is a library for text classification and word representation. It includes tools for training word embeddings and text classification models efficiently, making it suitable for large-scale applications.

These libraries provide a range of functionalities, from basic text processing to advanced deep learning models, catering to the diverse needs of NLP practitioners and researchers. The choice of library often depends on the specific requirements of the project and the preferred programming language.

# **Virtual Assistants:**
Virtual Assistants (VAs) are interactive software applications that use Natural Language Processing (NLP) and other technologies to understand and respond to user queries or commands in natural language. These assistants are designed to simulate human-like interactions and help users perform various tasks. Here's how NLP is crucial in the context of virtual assistants:

1. **Speech Recognition:**

   - Virtual assistants use NLP techniques for speech recognition to convert spoken language into text. This allows users to interact with the assistant using voice commands.

2. **Natural Language Understanding (NLU):**

   - NLU is a key component of NLP that enables virtual assistants to comprehend the meaning and intent behind user queries. It involves tasks such as entity recognition, sentiment analysis, and parsing to understand the context of the conversation.

3. **Intent Recognition:**

   - Virtual assistants use NLP to identify the user's intent, determining what action or information the user is seeking. This is crucial for providing accurate and relevant responses.

4. **Dialog Management:**

   - NLP plays a role in managing the flow of the conversation. Virtual assistants use dialog management systems to keep track of the context, maintain coherence, and understand the user's preferences over the course of the interaction.

5. **Text-to-Speech (TTS):**

   - NLP is employed in the text-to-speech conversion process, allowing virtual assistants to respond to users with synthesized, natural-sounding speech.

6. **Knowledge Retrieval:**

   - Virtual assistants often need access to external information or databases to provide relevant answers. NLP is used to retrieve and understand information from various sources.

7. **Context Awareness:**

   - NLP helps virtual assistants maintain context throughout a conversation. Understanding the context is essential for interpreting ambiguous queries and providing accurate responses.

8. **Multimodal Interaction:**

   - NLP facilitates multimodal interactions, where virtual assistants can understand and respond to a combination of inputs such as text, voice, and images. This enhances the overall user experience.

9. **Sentiment Analysis:**

   - Understanding the sentiment expressed by the user helps virtual assistants tailor responses appropriately. NLP-based sentiment analysis helps in gauging user emotions or opinions.

10. **Task Automation:**

    - NLP enables virtual assistants to automate tasks by understanding and executing user commands. This can include setting reminders, sending messages, making reservations, and more.

Examples of popular virtual assistants that leverage NLP include:

- **Siri (Apple):** Available on Apple devices, Siri uses NLP for voice recognition, natural language understanding, and task execution.

- **Google Assistant:** Integrated into Android devices and available on various platforms, Google Assistant relies on NLP for understanding and responding to user queries.

- **Amazon Alexa:** Powering Amazon Echo devices, Alexa utilizes NLP to interpret voice commands, answer questions, and perform various tasks.

The integration of NLP in virtual assistants enhances their ability to understand and respond to users in a more human-like manner, making them valuable tools for hands-free interaction and task assistance.

# **Chatbots:**
Chatbots are computer programs designed to simulate conversation with human users, typically through text-based or voice-based interactions. Natural Language Processing (NLP) plays a crucial role in the development and functionality of chatbots. Here's how NLP is essential in the context of chatbots:

1. **Text Understanding:**

   - NLP helps chatbots understand and interpret user input. It involves tasks such as tokenization, part-of-speech tagging, and named entity recognition to break down and analyze the user's message.

2. **Intent Recognition:**

   - NLP is employed to identify the user's intent behind a message. Chatbots use intent recognition to understand what action or information the user is seeking, allowing them to provide relevant responses.

3. **Entity Recognition:**

   - Chatbots use NLP techniques like named entity recognition to identify and extract specific entities mentioned in user messages, such as names, locations, dates, or product names.

4. **Dialog Management:**

   - NLP helps in managing the flow of conversation. Chatbots use dialog management systems to keep track of context, handle multi-turn interactions, and provide coherent responses based on the conversation history.

5. **Sentiment Analysis:**

   - NLP-based sentiment analysis is employed to understand the emotional tone expressed in user messages. This helps chatbots gauge user sentiment and respond appropriately, whether it's addressing concerns or providing positive reinforcement.

6. **Context Awareness:**

   - NLP allows chatbots to maintain context throughout a conversation. Understanding context is crucial for interpreting ambiguous queries and ensuring that responses are relevant to the ongoing discussion.

7. **Text Generation:**

   - In some cases, chatbots use NLP techniques for text generation to compose coherent and contextually relevant responses. This can involve completing prompts, generating suggestions, or even creating entirely new sentences.

8. **Multi-language Support:**

   - NLP facilitates the development of chatbots that can understand and respond in multiple languages. This is particularly important for chatbots deployed in diverse linguistic environments.

9. **FAQ Chatbots:**

   - NLP is used in the development of Frequently Asked Questions (FAQ) chatbots. These chatbots are trained to understand common queries and provide predefined responses, making them suitable for customer support and information retrieval.

10. **Continuous Learning:**

    - NLP can be employed to enable chatbots to learn from user interactions over time. Through machine learning algorithms, chatbots can adapt and improve their performance based on user feedback and new data.

Examples of popular chatbots that leverage NLP include:

- **Facebook Messenger Bots:** Businesses and developers use Facebook Messenger chatbots that employ NLP for natural language understanding and interaction.

- **Microsoft's Azure Bot Service:** Offers tools and services for building intelligent, NLP-driven bots that can be deployed on various platforms.

- **Google's Dialogflow:** A development suite for building conversational interfaces, utilizing NLP for intent recognition and entity extraction.

The integration of NLP in chatbots enhances their ability to provide more human-like and contextually relevant interactions, making them valuable tools for customer support, information retrieval, and various other applications.

**Language Translation**,
Language translatiion often referred to as machine translation, is a Natural Language Processing (NLP) application that involves automatically translating text or speech from one language to another. This is a complex task that requires an understanding of the semantic and syntactic structures of different languages. Here's how language translation works in the context of NLP:

1. **Text Preprocessing:**
   - The input text undergoes preprocessing, including tokenization, where it is broken down into individual words or phrases. This step helps in analyzing and translating smaller units of text.

2. **Statistical Machine Translation (SMT) or Neural Machine Translation (NMT):**
   - Two main approaches are used for machine translation:
     - **Statistical Machine Translation (SMT):** It relies on statistical models that learn patterns and relationships between words and phrases in parallel corpora (aligned texts in two or more languages). Common SMT models include phrase-based and statistical alignment models.
     - **Neural Machine Translation (NMT):** This newer approach uses neural networks, particularly sequence-to-sequence models, to learn direct mappings between input and output sequences. Transformer-based models, such as BERT and GPT, have been successful in NMT tasks.

3. **Training the Translation Model:**
   - For both SMT and NMT, the translation model is trained on large bilingual datasets. These datasets consist of pairs of sentences in the source language and their corresponding translations in the target language. During training, the model learns to associate input sequences with their correct translations.

4. **Word Embeddings and Representation:**
   - Word embeddings are used to represent words in a continuous vector space. These embeddings capture semantic relationships between words, helping the translation model understand the meaning of words in context.

5. **Attention Mechanism (NMT):**
   - In NMT models, attention mechanisms are often used to focus on different parts of the input sequence when generating each part of the output sequence. This helps the model handle long-range dependencies and improves translation accuracy.

6. **Decoding:**
   - During the decoding phase, the translation model generates the target-language output based on the learned associations. Beam search or greedy decoding strategies are commonly used to find the most likely translation.

7. **Evaluation Metrics:**
   - Translation models are evaluated using metrics such as BLEU (Bilingual Evaluation Understudy), which measures the overlap between predicted and reference translations. Other metrics include METEOR, ROUGE, and TER.

8. **Post-Processing:**
   - The translated text may undergo post-processing to ensure grammatical correctness, fluency, and idiomatic expression in the target language.

Applications of Language Translation in NLP:
- **Cross-Language Communication:** Enabling communication between speakers of different languages.
- **Global Business:** Facilitating international business by translating documents, websites, and communications.
- **Content Localization:** Adapting content to specific cultural and linguistic contexts for global audiences.
- **Research and Literature:** Translating research papers, literature, and academic materials for wider dissemination.
- **Humanitarian Aid:** Providing translation services in emergency situations and refugee support to aid communication.

Language translation in NLP continues to advance with the development of more sophisticated models, such as multilingual transformers, and the ongoing exploration of unsupervised and semi-supervised learning techniques for translation tasks.
has context menu

# **Confusion Matrix:shows performance of a classification algorithm.**
A confusion matrix is a table used in machine learning and statistics to evaluate the performance of a classification algorithm. It provides a summary of the classification results, showing the number of true positive (TP), true negative (TN), false positive (FP), and false negative (FN) predictions made by the model. These metrics are particularly useful for binary classification problems, where there are only two classes (positive and negative), but can be extended to multi-class problems as well.

Here's a breakdown of the terms used in a confusion matrix:

1. True Positive (TP): The number of instances correctly predicted as positive.

2. True Negative (TN): The number of instances correctly predicted as negative.

3. False Positive (FP): The number of instances incorrectly predicted as positive. Also known as Type I error.

4. False Negative (FN): The number of instances incorrectly predicted as negative. Also known as Type II error.

The confusion matrix is typically organized in a 2x2 table like this:

```
                Predicted Positive     Predicted Negative
Actual Positive        TP                     FN
Actual Negative        FP                     TN
```

From these values, various performance metrics can be calculated, such as:

- **Accuracy:** (TP + TN) / (TP + TN + FP + FN)
- **Precision (Positive Predictive Value):correctly predicted positive observations/total predicted positives..** TP / (TP + FP)
- **Recall (Sensitivity, True Positive Rate):correctly predicted positive observations / total actual positives.** TP / (TP + FN)
- **Specificity (True Negative Rate):** TN / (TN + FP)
- **F1 Score:** 2 * (Precision * Recall) / (Precision + Recall)

These metrics help assess the overall performance of a classification model, especially in scenarios where one metric may be more important than others depending on the context of the problem.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
path='/content/spam 1.tsv'
data=pd.read_csv(path, sep='\t')
df=pd.DataFrame(data)
df.head()

label                                            message  length  punct
0   ham  Go until jurong point, crazy.. Available only ...     111      9
1   ham                      Ok lar... Joking wif u oni...      29      6
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...     155      6
3   ham  U dun say so early hor... U c already then say...      49      6
4   ham  Nah I don't think he goes to usf, he lives aro...      61      2

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   label    5572 non-null   object
 1   message  5572 non-null   object
 2   length   5572 non-null   int64 
 3   punct    5572 non-null   int64 
dtypes: int64(2), object(2)
memory usage: 174.2+ KB


In [6]:
df.describe()

length        punct
count  5572.000000  5572.000000
mean     80.489950     4.177495
std      59.942907     4.623919
min       2.000000     0.000000
25%      36.000000     2.000000
50%      62.000000     3.000000
75%     122.000000     6.000000
max     910.000000   133.000000

In [7]:
df.describe(exclude='number')

label                 message
count   5572                    5572
unique     2                    5169
top      ham  Sorry, I'll call later
freq    4825                      30

In [8]:
df.isnull().sum()

label      0
message    0
length     0
punct      0
dtype: int64

In [9]:
df.label.value_counts()

ham     4825
spam     747
Name: label, dtype: int64

In [10]:
df.label.value_counts()/len(df)

ham     0.865937
spam    0.134063
Name: label, dtype: float64

In [12]:
ham_df = df[df.label=='ham']
spam_df = df[df.label=='spam']
ham_df.head()

label                                            message  length  punct
0   ham  Go until jurong point, crazy.. Available only ...     111      9
1   ham                      Ok lar... Joking wif u oni...      29      6
3   ham  U dun say so early hor... U c already then say...      49      6
4   ham  Nah I don't think he goes to usf, he lives aro...      61      2
6   ham  Even my brother is not like to speak with me. ...      77      2

In [13]:
spam_df.head()

label                                            message  length  punct
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...     155      6
5   spam  FreeMsg Hey there darling it's been 3 week's n...     147      8
8   spam  WINNER!! As a valued network customer you have...     157      6
9   spam  Had your mobile 11 months or more? U R entitle...     154      2
11  spam  SIX chances to win CASH! From 100 to 20,000 po...     136      8

In [15]:
ham_df.shape, spam_df.shape

((4825, 4), (747, 4))

In [18]:
ham_df = ham_df.sample(spam_df.shape[0])#sample the ham_df to have the same number of rows as spam_df

In [19]:
ham_df.shape, spam_df.shape

((747, 4), (747, 4))

In [20]:
data = ham_df.append(spam_df, ignore_index=True)

<ipython-input-20-2a46ae76b8b8>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = ham_df.append(spam_df, ignore_index=True)


In [21]:
data.shape

(1494, 4)

In [22]:
data['label'].value_counts()#balanced data

ham     747
spam    747
Name: label, dtype: int64

In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test =  train_test_split(data['message'], data['label'], test_size = 0.2, random_state =0, shuffle = True)

In [26]:
X_train, X_test, y_train, y_test

(465                               We're finally ready fyi
 1229    Do you want a New Nokia 3510i Colour Phone Del...
 1400    Bored housewives! Chat n date now! 0871750.77....
 1017    Call from 08702490080 - tells u 2 call 0906635...
 425            Hanging out with my brother and his family
                               ...                        
 763     Your free ringtone is waiting to be collected....
 835     XCLUSIVE@CLUBSAISAI 2MOROW 28/5 SOIREE SPECIAL...
 1216    Dorothy@kiefer.com (Bank of Granite issues Str...
 559                Except theres a chick with huge boobs.
 684     Do well :)all will for little time. Thing of g...
 Name: message, Length: 1195, dtype: object,
 799     Ur cash-balance is currently 500 pounds - to m...
 1047    FreeMsg: Hey - I'm Buffy. 25 and love to satis...
 1436    TheMob>Hit the link to get a premium Pink Pant...
 54                       Nan sonathaya soladha. Why boss?
 793     Think ur smart ? Win £200 this week in our wee...
           

# **Building the Model (Random Forest)**

In [27]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline

In [28]:
classifier = Pipeline([("tfidf", TfidfVectorizer()) , ("classifier", RandomForestClassifier(n_estimators=100))])
classifier.fit(X_train, y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()),
                ('classifier', RandomForestClassifier())])

**TfidfVectorizer:** This part of the pipeline converts a collection of raw text documents to a matrix of TF-IDF features. It tokenizes the text, counts the term frequencies, and applies the TF-IDF transformation to create a numerical representation of the text data.

**RandomForestClassifier:** This part of the pipeline is a machine learning model, specifically a Random Forest classifier. It is an ensemble model that builds multiple decision trees and merges them together to get a more accurate and stable prediction.

**Pipeline:** This class in scikit-learn allows you to streamline a lot of the routine processes, making it easier to set up and evaluate complex workflows. In this case, it combines the TF-IDF vectorizer and the Random Forest classifier into a single object.

**TF-IDF** stands for Term Frequency-Inverse Document Frequency. It is a numerical statistic that reflects how important a word is to a document in a collection or corpus. The TF-IDF value increases proportionally to the number of times a word appears in a document but is offset by the frequency of the word in the corpus. This helps in highlighting words that are unique to a specific document.

In [29]:
y_pred = classifier.predict(X_test)

In [30]:
y_test, y_pred

(799     spam
 1047    spam
 1436    spam
 54       ham
 793     spam
         ... 
 621      ham
 140      ham
 1433    spam
 693      ham
 39       ham
 Name: label, Length: 299, dtype: object,
 array(['spam', 'spam', 'spam', 'ham', 'spam', 'spam', 'ham', 'ham', 'ham',
        'ham', 'spam', 'ham', 'ham', 'spam', 'spam', 'spam', 'spam', 'ham',
        'spam', 'spam', 'spam', 'ham', 'spam', 'spam', 'ham', 'spam',
        'ham', 'ham', 'spam', 'ham', 'ham', 'spam', 'spam', 'spam', 'spam',
        'spam', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'spam', 'ham',
        'ham', 'spam', 'ham', 'ham', 'spam', 'spam', 'ham', 'spam', 'ham',
        'spam', 'spam', 'spam', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham',
        'ham', 'spam', 'spam', 'ham', 'ham', 'ham', 'spam', 'spam', 'spam',
        'spam', 'spam', 'ham', 'ham', 'spam', 'spam', 'ham', 'ham', 'ham',
        'spam', 'ham', 'ham', 'ham', 'ham', 'spam', 'spam', 'ham', 'spam',
        'ham', 'ham', 'spam', 'ham', 'ham', 'spam', 'spa

In [31]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

In [35]:
print(classification_report(y_test, y_pred))#shows the main classification metrics for a classification model
# Precision :correctly predicted positive observations/total predicted positives.
# Recall (Sensitivity) : correctly predicted positive observations / all observations in the actual class.
# F1-score : the weighted average of precision and recall.
# Support : the number of actual occurrences of the class in the specified dataset.

              precision    recall  f1-score   support

         ham       0.93      0.99      0.96       151
        spam       0.99      0.92      0.95       148

    accuracy                           0.96       299
   macro avg       0.96      0.96      0.96       299
weighted avg       0.96      0.96      0.96       299



In [32]:
accuracy_score(y_test, y_pred)

0.9565217391304348

In [33]:
confusion_matrix(y_test, y_pred)

array([[150,   1],
       [ 12, 136]])

# **Building SVM Model**

In [36]:
from sklearn.svm import SVC

In [38]:
svm = Pipeline([("tfidf", TfidfVectorizer()) , ("classifier", SVC(C = 100, gamma='auto'))])
svm.fit(X_train, y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()),
                ('classifier', SVC(C=100, gamma='auto'))])

In [39]:
y_pred = svm.predict(X_test)

In [42]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         ham       0.90      0.99      0.95       151
        spam       0.99      0.89      0.94       148

    accuracy                           0.94       299
   macro avg       0.95      0.94      0.94       299
weighted avg       0.95      0.94      0.94       299



In [40]:
accuracy_score(y_test, y_pred)

0.9431438127090301

In [41]:
confusion_matrix(y_test, y_pred)

array([[150,   1],
       [ 16, 132]])

In [44]:
test1 = ['Hello, You are learning natural Language Processing']
test2 = ['Hope you are doing good and learning new things !']
test3 = ['Congratulations, You won a lottery ticket worth $100 Million ! To claim call on 446677']
print(classifier.predict(test1))
print(classifier.predict(test2))
print(classifier.predict(test3))

['ham']
['ham']
['spam']


# **Restaurant Review Classification with NLTK**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [36]:
path='/content/Restaurant_Reviews.tsv'
data=pd.read_csv(path, sep='\t',quoting=3)#quotes non numeric values in csv file.
df=pd.DataFrame(data)
df.head()

Review  Liked
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1

In [3]:
import re
import nltk
nltk.download('stopwords')#words with little value

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [4]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer#for stemming/rooting the words

In [5]:
df.Review[0]

'Wow... Loved this place.'

In [6]:
data.Review[1]

'Crust is not good.'

In [7]:
data.Review[2]

'Not tasty and the texture was just nasty.'

In [8]:
review = re.sub('[^a-zA-Z]', ' ', data['Review'][0])# removing any non alphbetical char
review

'Wow    Loved this place '

In [10]:
review = review.lower()
review

'wow    loved this place '

In [12]:
review = re.sub('[^a-zA-Z]', ' ', data['Review'][0])
review = review.lower()
review = review.split()#gives list
review

['wow', 'loved', 'this', 'place']

In [14]:
review = [w for w in review if not w in set(stopwords.words('english'))]
review
#stopwords.words('english')-->gives list of stopwords=words with lil value

['wow', 'loved', 'place']

# **Stemming: rooting**

In [19]:
review = re.sub('[^a-zA-Z]',' ',data['Review'][0])
review = review.lower()
review =review.split()
ps = PorterStemmer()
review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
review # only root words included

['wow', 'love', 'place']

In [20]:
review = ' '.join(review)
review

'wow love place'

In [21]:
type(review)

str

In [23]:
corpus = []
for i in range(0,1000):
    review = re.sub('[^a-zA-Z]',' ',data['Review'][i]) # replace 0 by i
    review = review.lower()
    review =review.split()
    ps = PorterStemmer()
    review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))] # taking all the words in review except stop words
    review = ' '.join(review)
    corpus.append(review)
corpus

['wow love place',
 'crust good',
 'tasti textur nasti',
 'stop late may bank holiday rick steve recommend love',
 'select menu great price',
 'get angri want damn pho',
 'honeslti tast fresh',
 'potato like rubber could tell made ahead time kept warmer',
 'fri great',
 'great touch',
 'servic prompt',
 'would go back',
 'cashier care ever say still end wayyy overpr',
 'tri cape cod ravoli chicken cranberri mmmm',
 'disgust pretti sure human hair',
 'shock sign indic cash',
 'highli recommend',
 'waitress littl slow servic',
 'place worth time let alon vega',
 'like',
 'burritto blah',
 'food amaz',
 'servic also cute',
 'could care less interior beauti',
 'perform',
 'right red velvet cake ohhh stuff good',
 'never brought salad ask',
 'hole wall great mexican street taco friendli staff',
 'took hour get food tabl restaur food luke warm sever run around like total overwhelm',
 'worst salmon sashimi',
 'also combo like burger fri beer decent deal',
 'like final blow',
 'found place acc

In [43]:
from sklearn.feature_extraction.text import CountVectorizer#converts a collection of text documents to a count matrix
cv = CountVectorizer(max_features=1500)
x = cv.fit_transform(corpus).toarray()
print(x)
print(x.size)
# each no in each row represents no of times a words appear in the document.

[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]]
27


In [37]:
# Example:CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer

# Sample documents
corpus = ["This is the first document.", "This document is the second document.", "And this is the third one."]

# Create a CountVectorizer with a maximum of 1500 features (unique words)
cv = CountVectorizer(max_features=1500)

# Transform the text data into a document-term matrix
x = cv.fit_transform(corpus).toarray()

# Print the document-term matrix
print(x)


[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]]


In [25]:
x.shape

(1000, 1500)

In [27]:
y =df.iloc[:, 1].values
y

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,

In [28]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20, random_state = 0)

In [29]:
x_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [30]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_train, y_train)

GaussianNB()

In [31]:
y_pred = classifier.predict(x_test)

In [32]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [33]:
confusion_matrix(y_test, y_pred)

array([[55, 42],
       [12, 91]])

In [34]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.82      0.57      0.67        97
           1       0.68      0.88      0.77       103

    accuracy                           0.73       200
   macro avg       0.75      0.73      0.72       200
weighted avg       0.75      0.73      0.72       200



In [35]:
accuracy_score(y_test, y_pred)

0.73

# **Text Summarization**
Text summarization is a useful tool for various text applications that aims to highlight important information within a large corpus

With the outburst of information on the web, Text summarization helps to extract useful information
Why text summarization ?

Text summarization reduces the reading time
Makes selection process much easier
Improves effectiveness of indexing
Autometic text summarization is less bias than humans
With the Autometic text summarization, the number of documents to be proceeded increases

In [44]:
import spacy
from spacy.lang.en.stop_words import STOP_WORDS
from string import punctuation

In [45]:
nlp = spacy.load('en_core_web_sm')

In [48]:
text="""Pushpa Shrestha is an accomplished individual with a Ph.D. in Mathematics, demonstrating his passion for the intricacies of numerical analysis and mathematical exploration. At 34 years of age, he hails from Nepal, where he has not only pursued his education but has also made significant contributions to the field of mathematics.
His linguistic versatility is impressive, as he is fluent in Hindi, Nepali, and English, showcasing his dedication to effective communication across multiple languages. Beyond his academic pursuits, Pushpa wears different hats, serving as both a dedicated Math teacher and a skilled data engineer.
His desire to further expand his expertise has led him to aspire to become a data scientist, a role that combines his passion for mathematics with cutting-edge data analytics.
Pushpa's professional journey has taken him to various corners of the world. He has traveled extensively, exploring the diverse cultures of Nepal, China, India, Dubai, Qatar, the USA, Mexico, and Canada. These experiences have not only broadened his worldview but have also enriched his understanding of the global landscape.
In addition to his academic and professional pursuits, Pushpa is a well-rounded individual who finds joy in various aspects of life. He has a keen interest in sports, particularly football, where he not only appreciates the game but actively engages in playing it. His love for nature is evident, possibly influenced by his diverse travel experiences.
Pushpa is not just an academic and professional achiever; he is also a loving spouse. Balancing his personal and professional life, he finds solace in the company of his family and values the warmth of his relationships. Furthermore, his appreciation for literature and cinema adds a creative dimension to his personality, allowing him to find inspiration and relaxation in the world of books and films.
As Pushpa Shrestha continues to navigate his journey, his aspirations to contribute to the ever-evolving field of data science reflect his commitment to intellectual growth and innovation. With a solid foundation in mathematics, coupled with his experiences and diverse skill set, Pushpa stands poised to make meaningful contributions to the dynamic world of data analytics."""

In [49]:
stopwords = list(STOP_WORDS)

In [50]:
doc = nlp(text) # applied tokenization

In [51]:
tokens = [token.text for token in doc]
print(tokens)## as you can see in output, the punctuation and stop words are also the part of tokens

['Pushpa', 'Shrestha', 'is', 'an', 'accomplished', 'individual', 'with', 'a', 'Ph.D.', 'in', 'Mathematics', ',', 'demonstrating', 'his', 'passion', 'for', 'the', 'intricacies', 'of', 'numerical', 'analysis', 'and', 'mathematical', 'exploration', '.', 'At', '34', 'years', 'of', 'age', ',', 'he', 'hails', 'from', 'Nepal', ',', 'where', 'he', 'has', 'not', 'only', 'pursued', 'his', 'education', 'but', 'has', 'also', 'made', 'significant', 'contributions', 'to', 'the', 'field', 'of', 'mathematics', '.', '\n', 'His', 'linguistic', 'versatility', 'is', 'impressive', ',', 'as', 'he', 'is', 'fluent', 'in', 'Hindi', ',', 'Nepali', ',', 'and', 'English', ',', 'showcasing', 'his', 'dedication', 'to', 'effective', 'communication', 'across', 'multiple', 'languages', '.', 'Beyond', 'his', 'academic', 'pursuits', ',', 'Pushpa', 'wears', 'different', 'hats', ',', 'serving', 'as', 'both', 'a', 'dedicated', 'Math', 'teacher', 'and', 'a', 'skilled', 'data', 'engineer', '.', '\n', 'His', 'desire', 'to', '

In [52]:
punctuation # list of punctuations

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [53]:
punctuation = punctuation + '\n' # Add new line (\n) to punctuation

In [55]:
punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~\n'

# **Text Cleaning**

In [56]:
word_frequencies = {}

for word in doc:
  if word.text.lower() not in stopwords:
    if word.text.lower() not in punctuation:
      if word.text not in word_frequencies.keys():
        word_frequencies[word.text] = 1
      else:
        word_frequencies[word.text] += 1

# if any key is being introduced being first time the word of that occurence is onw
# when a word is being introduced second time, third time, so on..
# it will be incremented by 1

In [57]:
print(word_frequencies)

{'Pushpa': 7, 'Shrestha': 2, 'accomplished': 1, 'individual': 2, 'Ph.D.': 1, 'Mathematics': 1, 'demonstrating': 1, 'passion': 2, 'intricacies': 1, 'numerical': 1, 'analysis': 1, 'mathematical': 1, 'exploration': 1, '34': 1, 'years': 1, 'age': 1, 'hails': 1, 'Nepal': 2, 'pursued': 1, 'education': 1, 'significant': 1, 'contributions': 2, 'field': 2, 'mathematics': 3, 'linguistic': 1, 'versatility': 1, 'impressive': 1, 'fluent': 1, 'Hindi': 1, 'Nepali': 1, 'English': 1, 'showcasing': 1, 'dedication': 1, 'effective': 1, 'communication': 1, 'multiple': 1, 'languages': 1, 'academic': 3, 'pursuits': 2, 'wears': 1, 'different': 1, 'hats': 1, 'serving': 1, 'dedicated': 1, 'Math': 1, 'teacher': 1, 'skilled': 1, 'data': 5, 'engineer': 1, 'desire': 1, 'expand': 1, 'expertise': 1, 'led': 1, 'aspire': 1, 'scientist': 1, 'role': 1, 'combines': 1, 'cutting': 1, 'edge': 1, 'analytics': 2, 'professional': 4, 'journey': 2, 'taken': 1, 'corners': 1, 'world': 3, 'traveled': 1, 'extensively': 1, 'exploring'

In [58]:
max_frequency = max(word_frequencies.values())
max_frequency

7

In [60]:
# we are going to divide each of the value by 7 (max_frequency)
# so the normalized frequency can be achieved
for word in word_frequencies.keys():
  word_frequencies[word] = word_frequencies[word] / max_frequency
  print(word_frequencies)

{'Pushpa': 0.14285714285714285, 'Shrestha': 0.2857142857142857, 'accomplished': 0.14285714285714285, 'individual': 0.2857142857142857, 'Ph.D.': 0.14285714285714285, 'Mathematics': 0.14285714285714285, 'demonstrating': 0.14285714285714285, 'passion': 0.2857142857142857, 'intricacies': 0.14285714285714285, 'numerical': 0.14285714285714285, 'analysis': 0.14285714285714285, 'mathematical': 0.14285714285714285, 'exploration': 0.14285714285714285, '34': 0.14285714285714285, 'years': 0.14285714285714285, 'age': 0.14285714285714285, 'hails': 0.14285714285714285, 'Nepal': 0.2857142857142857, 'pursued': 0.14285714285714285, 'education': 0.14285714285714285, 'significant': 0.14285714285714285, 'contributions': 0.2857142857142857, 'field': 0.2857142857142857, 'mathematics': 0.42857142857142855, 'linguistic': 0.14285714285714285, 'versatility': 0.14285714285714285, 'impressive': 0.14285714285714285, 'fluent': 0.14285714285714285, 'Hindi': 0.14285714285714285, 'Nepali': 0.14285714285714285, 'English

# **Sentence tokenization**

In [61]:
sentence_tokens = [sent for sent in doc.sents]
print(sentence_tokens)

[Pushpa Shrestha is an accomplished individual with a Ph.D. in Mathematics, demonstrating his passion for the intricacies of numerical analysis and mathematical exploration., At 34 years of age, he hails from Nepal, where he has not only pursued his education but has also made significant contributions to the field of mathematics.
, His linguistic versatility is impressive, as he is fluent in Hindi, Nepali, and English, showcasing his dedication to effective communication across multiple languages., Beyond his academic pursuits, Pushpa wears different hats, serving as both a dedicated Math teacher and a skilled data engineer. 
, His desire to further expand his expertise has led him to aspire to become a data scientist, a role that combines his passion for mathematics with cutting-edge data analytics. 
, Pushpa's professional journey has taken him to various corners of the world., He has traveled extensively, exploring the diverse cultures of Nepal, China, India, Dubai, Qatar, the USA,

In [62]:
# calculate sentence score
sentence_score = {}

for sent in sentence_tokens:
  for word in sent:
    if word.text.lower() in word_frequencies.keys(): # if word_frequencies.keys() present there
      if sent not in sentence_score.keys():          # we will add normalized freq counts in each sentence
        sentence_score[sent] = word_frequencies[word.text.lower()]
      else:
        sentence_score[sent] += word_frequencies[word.text.lower()]

print(sentence_score)

{Pushpa Shrestha is an accomplished individual with a Ph.D. in Mathematics, demonstrating his passion for the intricacies of numerical analysis and mathematical exploration.: 0.2857142857142857, At 34 years of age, he hails from Nepal, where he has not only pursued his education but has also made significant contributions to the field of mathematics.
: 0.2857142857142857, His linguistic versatility is impressive, as he is fluent in Hindi, Nepali, and English, showcasing his dedication to effective communication across multiple languages.: 0.2040816326530612, Beyond his academic pursuits, Pushpa wears different hats, serving as both a dedicated Math teacher and a skilled data engineer. 
: 0.36734693877551017, His desire to further expand his expertise has led him to aspire to become a data scientist, a role that combines his passion for mathematics with cutting-edge data analytics. 
: 0.5510204081632655, Pushpa's professional journey has taken him to various corners of the world.: 0.224

# **Select 30% sentences with maximum score**

In [63]:
from heapq import nlargest

In [64]:
select_length = int(len(sentence_tokens)) * 0.3

In [66]:
print(select_length)# 30% of total sentences is almost 5

4.8


# **Getting the Summary**

In [67]:
# these 5 sentences represents summary of text
summary = nlargest(n=int(select_length), iterable=sentence_score, key = sentence_score.get)
print(summary)

[With a solid foundation in mathematics, coupled with his experiences and diverse skill set, Pushpa stands poised to make meaningful contributions to the dynamic world of data analytics., His desire to further expand his expertise has led him to aspire to become a data scientist, a role that combines his passion for mathematics with cutting-edge data analytics. 
, As Pushpa Shrestha continues to navigate his journey, his aspirations to contribute to the ever-evolving field of data science reflect his commitment to intellectual growth and innovation., In addition to his academic and professional pursuits, Pushpa is a well-rounded individual who finds joy in various aspects of life.]


In [69]:
# combine these sentences together
final_summary = [word.text for word in summary]
final_summary

['With a solid foundation in mathematics, coupled with his experiences and diverse skill set, Pushpa stands poised to make meaningful contributions to the dynamic world of data analytics.',
 'His desire to further expand his expertise has led him to aspire to become a data scientist, a role that combines his passion for mathematics with cutting-edge data analytics. \n',
 'As Pushpa Shrestha continues to navigate his journey, his aspirations to contribute to the ever-evolving field of data science reflect his commitment to intellectual growth and innovation.',
 'In addition to his academic and professional pursuits, Pushpa is a well-rounded individual who finds joy in various aspects of life.']

In [71]:
summary = ' '.join(final_summary)
print(summary)

With a solid foundation in mathematics, coupled with his experiences and diverse skill set, Pushpa stands poised to make meaningful contributions to the dynamic world of data analytics. His desire to further expand his expertise has led him to aspire to become a data scientist, a role that combines his passion for mathematics with cutting-edge data analytics. 
 As Pushpa Shrestha continues to navigate his journey, his aspirations to contribute to the ever-evolving field of data science reflect his commitment to intellectual growth and innovation. In addition to his academic and professional pursuits, Pushpa is a well-rounded individual who finds joy in various aspects of life.


In [73]:
len(text),len(summary) # comparing length of original text and summary

(2264, 685)